snapshot: lts-22.7 # GHC 9.6.4

packages:
- .

extra-deps:
# Cabal is pruned because process is a GHC boot package, and has to be specified
# again.
- Cabal-3.10.1.0@sha256:6d11adf7847d9734e7b02785ff831b5a0d11536bfbcefd6634b2b08411c63c94,12316
# Update once panty-0.9.4 is released:
- git: https://github.com/commercialhaskell/pantry.git
  commit: 8d434dc12a658dd050bd6cb01d207455a0db524a
# GHC 9.6.4 comes with process-1.6.17.0, which can segfault on macOS.
- process-1.6.18.0@sha256:cd0a3e0376b5a8525983d3131a31e52f9ffefc278ce635eec45a9d3987b8be3e,3025

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.6.4

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  hackage-security:
    cabal-syntax: true
  stack:
    developer-mode: true
